# Dependencies
# markdown:         cramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Tom Burrows
description:      Computer Science Student at Cambridge University
url:              https://tpmb.uk

baseurl:          /

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/tburrows13/tburrows13.github.io

social_links:
  github: tburrows13
  instagram: tom.p.burrows
  linkedin: tpmburrows
