# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Tom Burrows
description:      Software Engineer in Cambridge
url:              https://tpmb.uk

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/tburrows13/tburrows13.github.io